name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        PORT: ${{ secrets.REMOTE_PORT}}
        KEY: ${{ secrets.SERVER_SSH_KEY }}
      with:
        source: "."
        target: "/opt/mutatio/wallet/"

    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        PORT: ${{ secrets.REMOTE_PORT }}
        KEY: ${{ secrets.SERVER_SSH_KEY }}
        script: |
           pip install -r /opt/mutatio/wallet/requirements.txt 
           sudo systemctl restart mut-wallet.service
        
